% ---------------- plotting heart-shaped contour -------------------

% The value of heart-shaped curve is generated by Matlab
% The image resolution is processed by software origin
% The image resolution R is achieved by limiting the display range of the coordinate axis(origin)
% The specific display range through software origin, as follow:
% x[-144 144] y[-144 108] R=246×205
% x[-72 72] y[-72 54]  R=489×408
% x[-50 50] y[-50 37.5] R=704×586
% x[-40 40] y[-40 30]  R=879×732
% x[-30 30] y[-30 22.5] R=1172×976
% *x[-20 20] y[-20 15]  R=1756×1462
% *The maximum/minimum value of x/y that is closer to the curve cannot be further adjusted
% R=2019×1683 and R=4036×3366 are obtained through adjusting the size of the whole image

clear
clc

t = -180:1/50:180;
x = 16 * sind(t) .^ 3;
y = 13 * cosd(t) - 5 * cosd(2 * t) - 2 * cosd(3 * t) - cosd(4 * t);
